//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet.UI.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet.UI.Locale.LocaleResources.es", typeof(LocaleResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard.create", resourceCulture);
            }
        }
        
        public static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard.recover", resourceCulture);
            }
        }
        
        public static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        public static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        public static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }

        //Ordinals
        public static string Ordinal_first
        {
            get
            {
                return ResourceManager.GetString("Ordinal.first", resourceCulture);
            }
        }

        public static string Ordinal_second
        {
            get
            {
                return ResourceManager.GetString("Ordinal.second", resourceCulture);
            }
        }

        public static string Ordinal_third
        {
            get
            {
                return ResourceManager.GetString("Ordinal.third", resourceCulture);
            }
        }

        public static string Ordinal_fourth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.fourth", resourceCulture);
            }
        }

        public static string Ordinal_fifth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.fifth", resourceCulture);
            }
        }

        public static string Ordinal_sixth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.sixth", resourceCulture);
            }
        }

        public static string Ordinal_seventh
        {
            get
            {
                return ResourceManager.GetString("Ordinal.seventh", resourceCulture);
            }
        }

        public static string Ordinal_eighth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.eighth", resourceCulture);
            }
        }

        public static string Ordinal_ninth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.ninth", resourceCulture);
            }
        }

        public static string Ordinal_tenth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.tenth", resourceCulture);
            }
        }

        public static string Ordinal_eleventh
        {
            get
            {
                return ResourceManager.GetString("Ordinal.eleventh", resourceCulture);
            }
        }

        public static string Ordinal_twelveth
        {
            get
            {
                return ResourceManager.GetString("Ordinal.twelveth", resourceCulture);
            }
        }//End of ordinals


        public static string Pin_enter {
            get {
                return ResourceManager.GetString("Pin.enter", resourceCulture);
            }
        }
        
        public static string NowLoading_text {
            get {
                return ResourceManager.GetString("NowLoading.text", resourceCulture);
            }
        }
        
        public static string Transactions_title {
            get {
                return ResourceManager.GetString("Transactions.title", resourceCulture);
            }
        }
        
        public static string Transactions_empty {
            get {
                return ResourceManager.GetString("Transactions.empty", resourceCulture);
            }
        }
        
        public static string Transactions_empty_button {
            get {
                return ResourceManager.GetString("Transactions.empty.button", resourceCulture);
            }
        }
    }
}
