//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet.UI.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet.UI.Locale.LocaleResources.es", typeof(LocaleResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard.create", resourceCulture);
            }
        }
        
        public static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard.recover", resourceCulture);
            }
        }
        
        public static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        public static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        public static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }
        
        public static string Pin_enter {
            get {
                return ResourceManager.GetString("Pin.enter", resourceCulture);
            }
        }
        
        public static string NowLoading_text {
            get {
                return ResourceManager.GetString("NowLoading.text", resourceCulture);
            }
        }
        
        public static string Transactions_title {
            get {
                return ResourceManager.GetString("Transactions.title", resourceCulture);
            }
        }
        
        public static string Transactions_empty {
            get {
                return ResourceManager.GetString("Transactions.empty", resourceCulture);
            }
        }
        
        public static string Transactions_empty_button {
            get {
                return ResourceManager.GetString("Transactions.empty.button", resourceCulture);
            }
        }
        
        public static string Accounts_title {
            get {
                return ResourceManager.GetString("Accounts.title", resourceCulture);
            }
        }
        
        public static string AccountSelection_header {
            get {
                return ResourceManager.GetString("AccountSelection.header", resourceCulture);
            }
        }
        
        public static string AccountSelection_subheader {
            get {
                return ResourceManager.GetString("AccountSelection.subheader", resourceCulture);
            }
        }
        
        public static string AccountSelection_title {
            get {
                return ResourceManager.GetString("AccountSelection.title", resourceCulture);
            }
        }
        
        public static string AddAccount_button {
            get {
                return ResourceManager.GetString("AddAccount.button", resourceCulture);
            }
        }
        
        public static string AddAccount_header {
            get {
                return ResourceManager.GetString("AddAccount.header", resourceCulture);
            }
        }
        
        public static string AddAccount_subheader {
            get {
                return ResourceManager.GetString("AddAccount.subheader", resourceCulture);
            }
        }
        
        public static string AddAccount_title {
            get {
                return ResourceManager.GetString("AddAccount.title", resourceCulture);
            }
        }
        
        public static string AddAccount_close {
            get {
                return ResourceManager.GetString("AddAccount.close", resourceCulture);
            }
        }
        
        public static string AddAccount_entry {
            get {
                return ResourceManager.GetString("AddAccount.entry", resourceCulture);
            }
        }
        
        public static string AddAccount_options {
            get {
                return ResourceManager.GetString("AddAccount.options", resourceCulture);
            }
        }
        
        public static string AddAccount_color {
            get {
                return ResourceManager.GetString("AddAccount.color", resourceCulture);
            }
        }
        
        public static string AddAccount_createButton {
            get {
                return ResourceManager.GetString("AddAccount.createButton", resourceCulture);
            }
        }
        
        public static string Backup_button {
            get {
                return ResourceManager.GetString("Backup.button", resourceCulture);
            }
        }
        
        public static string Backup_header {
            get {
                return ResourceManager.GetString("Backup.header", resourceCulture);
            }
        }
        
        public static string Backup_subheader {
            get {
                return ResourceManager.GetString("Backup.subheader", resourceCulture);
            }
        }
        
        public static string Backup_title {
            get {
                return ResourceManager.GetString("Backup.title", resourceCulture);
            }
        }
        
        public static string BackupConfirm_exercise {
            get {
                return ResourceManager.GetString("BackupConfirm.exercise", resourceCulture);
            }
        }
        
        public static string BackupConfirm_header {
            get {
                return ResourceManager.GetString("BackupConfirm.header", resourceCulture);
            }
        }
        
        public static string BackupConfirm_warning {
            get {
                return ResourceManager.GetString("BackupConfirm.warning", resourceCulture);
            }
        }
        
        public static string BackupWord_header {
            get {
                return ResourceManager.GetString("BackupWord.header", resourceCulture);
            }
        }
        
        public static string BackupWord_next {
            get {
                return ResourceManager.GetString("BackupWord.next", resourceCulture);
            }
        }
        
        public static string BackupWord_previous {
            get {
                return ResourceManager.GetString("BackupWord.previous", resourceCulture);
            }
        }
        
        public static string BackupWord_title {
            get {
                return ResourceManager.GetString("BackupWord.title", resourceCulture);
            }
        }
        
        public static string Dashboard_menu {
            get {
                return ResourceManager.GetString("Dashboard.menu", resourceCulture);
            }
        }
        
        public static string Dashboard_receive {
            get {
                return ResourceManager.GetString("Dashboard.receive", resourceCulture);
            }
        }
        
        public static string Dashboard_send {
            get {
                return ResourceManager.GetString("Dashboard.send", resourceCulture);
            }
        }
        
        public static string Done_button {
            get {
                return ResourceManager.GetString("Done.button", resourceCulture);
            }
        }
        
        public static string FingerprintAuth_header {
            get {
                return ResourceManager.GetString("FingerprintAuth.header", resourceCulture);
            }
        }
        
        public static string FingerprintAuth_limitButtonAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.limitButtonAndroid", resourceCulture);
            }
        }
        
        public static string FingerprintAuth_spendingLimit {
            get {
                return ResourceManager.GetString("FingerprintAuth.spendingLimit", resourceCulture);
            }
        }
        
        public static string FingerprintAuth_switchAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchAndroid", resourceCulture);
            }
        }
        
        public static string FingerprintAuth_switchLabelIOS {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchLabelIOS", resourceCulture);
            }
        }
        
        public static string Backup_Close {
            get {
                return ResourceManager.GetString("Backup.Close", resourceCulture);
            }
        }
        
        public static string Backup_Skip {
            get {
                return ResourceManager.GetString("Backup.Skip", resourceCulture);
            }
        }
        
        public static string AccountSettings_Title {
            get {
                return ResourceManager.GetString("AccountSettings.Title", resourceCulture);
            }
        }
        
        public static string Send_button_send {
            get {
                return ResourceManager.GetString("Send.button_send", resourceCulture);
            }
        }
        
        public static string Send_title {
            get {
                return ResourceManager.GetString("Send.title", resourceCulture);
            }
        }
        
        public static string Ordinal_eighth {
            get {
                return ResourceManager.GetString("Ordinal.eighth", resourceCulture);
            }
        }
        
        public static string Ordinal_eleventh {
            get {
                return ResourceManager.GetString("Ordinal.eleventh", resourceCulture);
            }
        }
        
        public static string Ordinal_fifth {
            get {
                return ResourceManager.GetString("Ordinal.fifth", resourceCulture);
            }
        }
        
        public static string Ordinal_first {
            get {
                return ResourceManager.GetString("Ordinal.first", resourceCulture);
            }
        }
        
        public static string Ordinal_fourth {
            get {
                return ResourceManager.GetString("Ordinal.fourth", resourceCulture);
            }
        }
        
        public static string Ordinal_ninth {
            get {
                return ResourceManager.GetString("Ordinal.ninth", resourceCulture);
            }
        }
        
        public static string Ordinal_second {
            get {
                return ResourceManager.GetString("Ordinal.second", resourceCulture);
            }
        }
        
        public static string Ordinal_seventh {
            get {
                return ResourceManager.GetString("Ordinal.seventh", resourceCulture);
            }
        }
        
        public static string Ordinal_sixth {
            get {
                return ResourceManager.GetString("Ordinal.sixth", resourceCulture);
            }
        }
        
        public static string Ordinal_tenth {
            get {
                return ResourceManager.GetString("Ordinal.tenth", resourceCulture);
            }
        }
        
        public static string Ordinal_third {
            get {
                return ResourceManager.GetString("Ordinal.third", resourceCulture);
            }
        }
        
        public static string Ordinal_twelveth {
            get {
                return ResourceManager.GetString("Ordinal.twelveth", resourceCulture);
            }
        }
        
        public static string Alert_irreversible {
            get {
                return ResourceManager.GetString("Alert.irreversible", resourceCulture);
            }
        }
        
        public static string Button_no {
            get {
                return ResourceManager.GetString("Button.no", resourceCulture);
            }
        }
        
        public static string Button_yes {
            get {
                return ResourceManager.GetString("Button.yes", resourceCulture);
            }
        }
        
        public static string Ordinal_eighteenth {
            get {
                return ResourceManager.GetString("Ordinal.eighteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_fifteenth {
            get {
                return ResourceManager.GetString("Ordinal.fifteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_fourteenth {
            get {
                return ResourceManager.GetString("Ordinal.fourteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_nineteenth {
            get {
                return ResourceManager.GetString("Ordinal.nineteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_seventeenth {
            get {
                return ResourceManager.GetString("Ordinal.seventeenth", resourceCulture);
            }
        }
        
        public static string Ordinal_sixteenth {
            get {
                return ResourceManager.GetString("Ordinal.sixteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_thirteenth {
            get {
                return ResourceManager.GetString("Ordinal.thirteenth", resourceCulture);
            }
        }
        
        public static string Ordinal_twentieth {
            get {
                return ResourceManager.GetString("Ordinal.twentieth", resourceCulture);
            }
        }
        
        public static string Ordinal_twenty_first {
            get {
                return ResourceManager.GetString("Ordinal.twenty-first", resourceCulture);
            }
        }
        
        public static string Ordinal_twenty_fourth {
            get {
                return ResourceManager.GetString("Ordinal.twenty-fourth", resourceCulture);
            }
        }
        
        public static string Ordinal_twenty_second {
            get {
                return ResourceManager.GetString("Ordinal.twenty-second", resourceCulture);
            }
        }
        
        public static string Ordinal_twenty_third {
            get {
                return ResourceManager.GetString("Ordinal.twenty-third", resourceCulture);
            }
        }
        
        public static string Send_economyFee {
            get {
                return ResourceManager.GetString("Send.economyFee", resourceCulture);
            }
        }
        
        public static string Send_estConfirmation {
            get {
                return ResourceManager.GetString("Send.estConfirmation", resourceCulture);
            }
        }
        
        public static string Send_highFee {
            get {
                return ResourceManager.GetString("Send.highFee", resourceCulture);
            }
        }
        
        public static string Send_normalFee {
            get {
                return ResourceManager.GetString("Send.normalFee", resourceCulture);
            }
        }
        
        public static string Send_transactionFee {
            get {
                return ResourceManager.GetString("Send.transactionFee", resourceCulture);
            }
        }
    }
}
