//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet.UI.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HodlWallet.UI.Locale.LocaleResources", typeof(LocaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD PATH.
        /// </summary>
        internal static string AccountInfo_HdPath {
            get {
                return ResourceManager.GetString("AccountInfo.HdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string AccountInfo_Id {
            get {
                return ResourceManager.GetString("AccountInfo.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string AccountInfo_Name {
            get {
                return ResourceManager.GetString("AccountInfo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        internal static string AccountInfo_Title {
            get {
                return ResourceManager.GetString("AccountInfo.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPRV (PRIVATE KEY).
        /// </summary>
        internal static string AccountInfo_XPrv {
            get {
                return ResourceManager.GetString("AccountInfo.XPrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPUB (PUBLIC KEY).
        /// </summary>
        internal static string AccountInfo_XPub {
            get {
                return ResourceManager.GetString("AccountInfo.XPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts_title {
            get {
                return ResourceManager.GetString("Accounts.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for this account..
        /// </summary>
        internal static string AccountSelection_header {
            get {
                return ResourceManager.GetString("AccountSelection.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from the options below which type of account you want to create..
        /// </summary>
        internal static string AccountSelection_subheader {
            get {
                return ResourceManager.GetString("AccountSelection.subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Account.
        /// </summary>
        internal static string AccountSelection_title {
            get {
                return ResourceManager.GetString("AccountSelection.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Control.
        /// </summary>
        internal static string AccountSettings_coincontrol {
            get {
                return ResourceManager.GetString("AccountSettings.coincontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string AccountSettings_info {
            get {
                return ResourceManager.GetString("AccountSettings.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string AccountSettings_title {
            get {
                return ResourceManager.GetString("AccountSettings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodl Wallet supports two different account types described below. Please select the account type you would like to create. Creating a new account has no effect on your existing accounts..
        /// </summary>
        internal static string AccountTypeSelection_description {
            get {
                return ResourceManager.GetString("AccountTypeSelection.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string AccountTypeSelection_doneButton {
            get {
                return ResourceManager.GetString("AccountTypeSelection.doneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates legacy bitcoin addresses that begin with 1. These addresses are supported by all bitcoin services but will lead to higher fees when sending than standard. Use this account type if the service or wallet you are sending to does not support the newest address standard..
        /// </summary>
        internal static string AccountTypeSelection_legacyDescription {
            get {
                return ResourceManager.GetString("AccountTypeSelection.legacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy.
        /// </summary>
        internal static string AccountTypeSelection_legacyTitle {
            get {
                return ResourceManager.GetString("AccountTypeSelection.legacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of account.
        /// </summary>
        internal static string AccountTypeSelection_pleaseSelect {
            get {
                return ResourceManager.GetString("AccountTypeSelection.pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newest bitcoin address standard. This will create addresses that begin with bc1 (Bech 32). This account type will help you save on fees but Bech 32 addresses may still not be supported by some bitcoin wallets and services..
        /// </summary>
        internal static string AccountTypeSelection_standardDescription {
            get {
                return ResourceManager.GetString("AccountTypeSelection.standardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string AccountTypeSelection_standardTitle {
            get {
                return ResourceManager.GetString("AccountTypeSelection.standardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account Type.
        /// </summary>
        internal static string AccountTypeSelection_title {
            get {
                return ResourceManager.GetString("AccountTypeSelection.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string AckRisk_button {
            get {
                return ResourceManager.GetString("AckRisk.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that not properly backing up my wallet can lead to loss of funds..
        /// </summary>
        internal static string AckRisk_term1 {
            get {
                return ResourceManager.GetString("AckRisk.term1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will not take a screen shot of my key..
        /// </summary>
        internal static string AckRisk_term2 {
            get {
                return ResourceManager.GetString("AckRisk.term2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that Hodl Wallet does not store a copy of this key and should I lose it Hodl Wallet can&apos;t help me recover my funds..
        /// </summary>
        internal static string AckRisk_term3 {
            get {
                return ResourceManager.GetString("AckRisk.term3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am ready to copy down the words of my Backup Recovery Key and store it..
        /// </summary>
        internal static string AckRisk_term4 {
            get {
                return ResourceManager.GetString("AckRisk.term4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Wallet.
        /// </summary>
        internal static string AckRisk_title {
            get {
                return ResourceManager.GetString("AckRisk.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string AddAccount_button {
            get {
                return ResourceManager.GetString("AddAccount.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AddAccount_close {
            get {
                return ResourceManager.GetString("AddAccount.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Color.
        /// </summary>
        internal static string AddAccount_color {
            get {
                return ResourceManager.GetString("AddAccount.color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string AddAccount_createButton {
            get {
                return ResourceManager.GetString("AddAccount.createButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AddAccount_entry {
            get {
                return ResourceManager.GetString("AddAccount.entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Update Image].
        /// </summary>
        internal static string AddAccount_header {
            get {
                return ResourceManager.GetString("AddAccount.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AddAccount_options {
            get {
                return ResourceManager.GetString("AddAccount.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bip141 Legacy.
        /// </summary>
        internal static string AddAccount_options_bip141 {
            get {
                return ResourceManager.GetString("AddAccount.options.bip141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bip84 Standard.
        /// </summary>
        internal static string AddAccount_options_bip84 {
            get {
                return ResourceManager.GetString("AddAccount.options.bip84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Account.
        /// </summary>
        internal static string AddAccount_placeholder {
            get {
                return ResourceManager.GetString("AddAccount.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a variety of account types..
        /// </summary>
        internal static string AddAccount_subheader {
            get {
                return ResourceManager.GetString("AddAccount.subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Account.
        /// </summary>
        internal static string AddAccount_title {
            get {
                return ResourceManager.GetString("AddAccount.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Copied to Clipboard.
        /// </summary>
        internal static string Address_copied {
            get {
                return ResourceManager.GetString("Address.copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible, are you sure?.
        /// </summary>
        internal static string Alert_irreversible {
            get {
                return ResourceManager.GetString("Alert.irreversible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Down Backup Recovery Key.
        /// </summary>
        internal static string Backup_button {
            get {
                return ResourceManager.GetString("Backup.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Backup_close {
            get {
                return ResourceManager.GetString("Backup.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your backup recovery key is the only way to restore your wallet if your phone is lost, stolen, broken or upgraded..
        /// </summary>
        internal static string Backup_header {
            get {
                return ResourceManager.GetString("Backup.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Backup_skip {
            get {
                return ResourceManager.GetString("Backup.skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will show you a list of words to write down on a piece of paper and keep safe..
        /// </summary>
        internal static string Backup_subheader {
            get {
                return ResourceManager.GetString("Backup.subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recovery Key.
        /// </summary>
        internal static string Backup_title {
            get {
                return ResourceManager.GetString("Backup.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the {0} word from your mnemonic:.
        /// </summary>
        internal static string BackupConfirm_exercise {
            get {
                return ResourceManager.GetString("BackupConfirm.exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the words to put them in the same order you wrote them down. Then Tap Next..
        /// </summary>
        internal static string BackupConfirm_header {
            get {
                return ResourceManager.GetString("BackupConfirm.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect mnemonic order please review your seed.
        /// </summary>
        internal static string BackupConfirm_incorrectOrder {
            get {
                return ResourceManager.GetString("BackupConfirm.incorrectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That word is not in your mnemonic..
        /// </summary>
        internal static string BackupConfirm_warning {
            get {
                return ResourceManager.GetString("BackupConfirm.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string BackupWord_done {
            get {
                return ResourceManager.GetString("BackupWord.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down each word in order and store it in a safe place..
        /// </summary>
        internal static string BackupWord_header {
            get {
                return ResourceManager.GetString("BackupWord.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string BackupWord_next {
            get {
                return ResourceManager.GetString("BackupWord.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic not found!.
        /// </summary>
        internal static string BackupWord_noMnemonic {
            get {
                return ResourceManager.GetString("BackupWord.noMnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string BackupWord_previous {
            get {
                return ResourceManager.GetString("BackupWord.previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recovery Key.
        /// </summary>
        internal static string BackupWord_title {
            get {
                return ResourceManager.GetString("BackupWord.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE.
        /// </summary>
        internal static string BalanceHeader_balance {
            get {
                return ResourceManager.GetString("BalanceHeader.balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string BalanceHeader_total {
            get {
                return ResourceManager.GetString("BalanceHeader.total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your biometric authentication to unlock your wallet and send money up to a set limit..
        /// </summary>
        internal static string BiometricAuth_header {
            get {
                return ResourceManager.GetString("BiometricAuth.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending limit: .
        /// </summary>
        internal static string BiometricAuth_spendingLimit {
            get {
                return ResourceManager.GetString("BiometricAuth.spendingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Authentication Spending Limit Screen..
        /// </summary>
        internal static string BiometricAuth_spendingLimitScreen {
            get {
                return ResourceManager.GetString("BiometricAuth.spendingLimitScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can customize your touch ID spending limit from the .
        /// </summary>
        internal static string BiometricAuth_subheader {
            get {
                return ResourceManager.GetString("BiometricAuth.subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Biometric Authentication for Hodl.
        /// </summary>
        internal static string BiometricAuth_switch {
            get {
                return ResourceManager.GetString("BiometricAuth.switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use biometric authentication..
        /// </summary>
        internal static string BiometricLogin_askAuth {
            get {
                return ResourceManager.GetString("BiometricLogin.askAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No biometrics authentication available, please check settings of the device..
        /// </summary>
        internal static string Biometrics_notAvailableWarning {
            get {
                return ResourceManager.GetString("Biometrics.notAvailableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometrics ID.
        /// </summary>
        internal static string Biometrics_title {
            get {
                return ResourceManager.GetString("Biometrics.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BiometricsSettings_close {
            get {
                return ResourceManager.GetString("BiometricsSettings.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Button_no {
            get {
                return ResourceManager.GetString("Button.no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Button_yes {
            get {
                return ResourceManager.GetString("Button.yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Dashboard_menu {
            get {
                return ResourceManager.GetString("Dashboard.menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string Dashboard_receive {
            get {
                return ResourceManager.GetString("Dashboard.receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Dashboard_send {
            get {
                return ResourceManager.GetString("Dashboard.send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin (BTC).
        /// </summary>
        internal static string DisplayCurrency_bitcoin {
            get {
                return ResourceManager.GetString("DisplayCurrency.bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Display Unit.
        /// </summary>
        internal static string DisplayCurrency_bitcoinDisplayUnit {
            get {
                return ResourceManager.GetString("DisplayCurrency.bitcoinDisplayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiat Currency Unit.
        /// </summary>
        internal static string DisplayCurrency_fiatCurrencyUnit {
            get {
                return ResourceManager.GetString("DisplayCurrency.fiatCurrencyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        internal static string DisplayCurrency_rate {
            get {
                return ResourceManager.GetString("DisplayCurrency.rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satoshi (SAT).
        /// </summary>
        internal static string DisplayCurrency_sats {
            get {
                return ResourceManager.GetString("DisplayCurrency.sats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Currency.
        /// </summary>
        internal static string DisplayCurrency_title {
            get {
                return ResourceManager.GetString("DisplayCurrency.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done_button {
            get {
                return ResourceManager.GetString("Done.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Error_ok {
            get {
                return ResourceManager.GetString("Error.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Home_title {
            get {
                return ResourceManager.GetString("Home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Login_cancel {
            get {
                return ResourceManager.GetString("Login.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Login_close {
            get {
                return ResourceManager.GetString("Login.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Authentication.
        /// </summary>
        internal static string Login_useBiometric {
            get {
                return ResourceManager.GetString("Login.useBiometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Login_usePin {
            get {
                return ResourceManager.GetString("Login.usePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the way of autentication..
        /// </summary>
        internal static string Login_wayAuthentication {
            get {
                return ResourceManager.GetString("Login.wayAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Control.
        /// </summary>
        internal static string Menu_coinControl {
            get {
                return ResourceManager.GetString("Menu.coinControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Menu_currency {
            get {
                return ResourceManager.GetString("Menu.currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string Menu_info {
            get {
                return ResourceManager.GetString("Menu.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        internal static string Menu_knowledge {
            get {
                return ResourceManager.GetString("Menu.knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Wallet.
        /// </summary>
        internal static string Menu_lock {
            get {
                return ResourceManager.GetString("Menu.lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Menu_network {
            get {
                return ResourceManager.GetString("Menu.network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Wallet.
        /// </summary>
        internal static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Sync Wallet.
        /// </summary>
        internal static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Menu_security {
            get {
                return ResourceManager.GetString("Menu.security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_settings {
            get {
                return ResourceManager.GetString("Menu.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu_title {
            get {
                return ResourceManager.GetString("Menu.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string Menu_wallet {
            get {
                return ResourceManager.GetString("Menu.wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Wallet.
        /// </summary>
        internal static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin to an address or generate a new one to receive.
        /// </summary>
        internal static string MyBitcoin_contextualInfo {
            get {
                return ResourceManager.GetString("MyBitcoin.contextualInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVE BITCOIN.
        /// </summary>
        internal static string MyBitcoin_receiveBitcoin {
            get {
                return ResourceManager.GetString("MyBitcoin.receiveBitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an address to receive Bitcoin.
        /// </summary>
        internal static string MyBitcoin_receiveBitcoinInfo {
            get {
                return ResourceManager.GetString("MyBitcoin.receiveBitcoinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND BITCOIN.
        /// </summary>
        internal static string MyBitcoin_sendBitcoin {
            get {
                return ResourceManager.GetString("MyBitcoin.sendBitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan an address and send Bitcoin.
        /// </summary>
        internal static string MyBitcoin_sendBitcoinInfo {
            get {
                return ResourceManager.GetString("MyBitcoin.sendBitcoinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND / RECEIVE.
        /// </summary>
        internal static string MyBitcoin_sendSlashReceive {
            get {
                return ResourceManager.GetString("MyBitcoin.sendSlashReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bitcoin.
        /// </summary>
        internal static string MyBitcoin_title {
            get {
                return ResourceManager.GetString("MyBitcoin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we get started you should know:
        ///
        ///Hodl Wallet is a non-custodial Bitcoin Wallet. This means you are the sole person with access to the bitcoin stored in this app.
        ///All you have to do is safety store the wallets backup recovery key and you&apos;ll always have access to you bitcoin..
        /// </summary>
        internal static string NewWallet_body {
            get {
                return ResourceManager.GetString("NewWallet.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NewWallet_button {
            get {
                return ResourceManager.GetString("NewWallet.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hodl Wallet.
        /// </summary>
        internal static string NewWallet_header {
            get {
                return ResourceManager.GetString("NewWallet.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Wallet.
        /// </summary>
        internal static string NewWallet_title {
            get {
                return ResourceManager.GetString("NewWallet.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Loading....
        /// </summary>
        internal static string NowLoading_text {
            get {
                return ResourceManager.GetString("NowLoading.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NEW WALLET.
        /// </summary>
        internal static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER WALLET.
        /// </summary>
        internal static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard.recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighteenth.
        /// </summary>
        internal static string Ordinal_eighteenth {
            get {
                return ResourceManager.GetString("Ordinal.eighteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eighth.
        /// </summary>
        internal static string Ordinal_eighth {
            get {
                return ResourceManager.GetString("Ordinal.eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleventh.
        /// </summary>
        internal static string Ordinal_eleventh {
            get {
                return ResourceManager.GetString("Ordinal.eleventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteenth.
        /// </summary>
        internal static string Ordinal_fifteenth {
            get {
                return ResourceManager.GetString("Ordinal.fifteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifth.
        /// </summary>
        internal static string Ordinal_fifth {
            get {
                return ResourceManager.GetString("Ordinal.fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string Ordinal_first {
            get {
                return ResourceManager.GetString("Ordinal.first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteenth.
        /// </summary>
        internal static string Ordinal_fourteenth {
            get {
                return ResourceManager.GetString("Ordinal.fourteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        internal static string Ordinal_fourth {
            get {
                return ResourceManager.GetString("Ordinal.fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineteenth.
        /// </summary>
        internal static string Ordinal_nineteenth {
            get {
                return ResourceManager.GetString("Ordinal.nineteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ninth.
        /// </summary>
        internal static string Ordinal_ninth {
            get {
                return ResourceManager.GetString("Ordinal.ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Ordinal_second {
            get {
                return ResourceManager.GetString("Ordinal.second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventeenth.
        /// </summary>
        internal static string Ordinal_seventeenth {
            get {
                return ResourceManager.GetString("Ordinal.seventeenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seventh.
        /// </summary>
        internal static string Ordinal_seventh {
            get {
                return ResourceManager.GetString("Ordinal.seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteenth.
        /// </summary>
        internal static string Ordinal_sixteenth {
            get {
                return ResourceManager.GetString("Ordinal.sixteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixth.
        /// </summary>
        internal static string Ordinal_sixth {
            get {
                return ResourceManager.GetString("Ordinal.sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenth.
        /// </summary>
        internal static string Ordinal_tenth {
            get {
                return ResourceManager.GetString("Ordinal.tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string Ordinal_third {
            get {
                return ResourceManager.GetString("Ordinal.third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteenth.
        /// </summary>
        internal static string Ordinal_thirteenth {
            get {
                return ResourceManager.GetString("Ordinal.thirteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelveth.
        /// </summary>
        internal static string Ordinal_twelveth {
            get {
                return ResourceManager.GetString("Ordinal.twelveth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twentieth.
        /// </summary>
        internal static string Ordinal_twentieth {
            get {
                return ResourceManager.GetString("Ordinal.twentieth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty-first.
        /// </summary>
        internal static string Ordinal_twenty_first {
            get {
                return ResourceManager.GetString("Ordinal.twenty-first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty-fourth.
        /// </summary>
        internal static string Ordinal_twenty_fourth {
            get {
                return ResourceManager.GetString("Ordinal.twenty-fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty-second.
        /// </summary>
        internal static string Ordinal_twenty_second {
            get {
                return ResourceManager.GetString("Ordinal.twenty-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twenty-third.
        /// </summary>
        internal static string Ordinal_twenty_third {
            get {
                return ResourceManager.GetString("Ordinal.twenty-third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        internal static string Pin_enter {
            get {
                return ResourceManager.GetString("Pin.enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PIN will be used to unlock your wallet and send money..
        /// </summary>
        internal static string Pin_header {
            get {
                return ResourceManager.GetString("Pin.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter PIN.
        /// </summary>
        internal static string Pin_redoTitle {
            get {
                return ResourceManager.GetString("Pin.redoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PIN.
        /// </summary>
        internal static string Pin_setTitle {
            get {
                return ResourceManager.GetString("Pin.setTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current PIN..
        /// </summary>
        internal static string Pin_updateHeader {
            get {
                return ResourceManager.GetString("Pin.updateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PIN.
        /// </summary>
        internal static string Pin_updateTitle {
            get {
                return ResourceManager.GetString("Pin.updateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this PIN. If you forget it, you won&apos;t be able to access your bitcoin..
        /// </summary>
        internal static string Pin_warning {
            get {
                return ResourceManager.GetString("Pin.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string PinPad_close {
            get {
                return ResourceManager.GetString("PinPad.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A New Pin.
        /// </summary>
        internal static string PinPad_Title {
            get {
                return ResourceManager.GetString("PinPad.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string PinSettings_close {
            get {
                return ResourceManager.GetString("PinSettings.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Spending Limits.
        /// </summary>
        internal static string PinSettings_pinSpendingLimits {
            get {
                return ResourceManager.GetString("PinSettings.pinSpendingLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Settings.
        /// </summary>
        internal static string PinSettings_title {
            get {
                return ResourceManager.GetString("PinSettings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Pin.
        /// </summary>
        internal static string PinSettings_updatePin {
            get {
                return ResourceManager.GetString("PinSettings.updatePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string QrCode_title {
            get {
                return ResourceManager.GetString("QrCode.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD AMOUNT.
        /// </summary>
        internal static string Receive_addAmount {
            get {
                return ResourceManager.GetString("Receive.addAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        internal static string Receive_amountLabel {
            get {
                return ResourceManager.GetString("Receive.amountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string Receive_clear {
            get {
                return ResourceManager.GetString("Receive.clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        internal static string Receive_share {
            get {
                return ResourceManager.GetString("Receive.share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Bitcoin.
        /// </summary>
        internal static string Receive_title {
            get {
                return ResourceManager.GetString("Receive.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIQUE ADDRESS.
        /// </summary>
        internal static string Receive_uniqueAddress {
            get {
                return ResourceManager.GetString("Receive.uniqueAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string Recover_alertButton {
            get {
                return ResourceManager.GetString("Recover.alertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the words you entered are either mispelled or invalid..
        /// </summary>
        internal static string Recover_alertHeader {
            get {
                return ResourceManager.GetString("Recover.alertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mnemonic.
        /// </summary>
        internal static string Recover_alertTitle {
            get {
                return ResourceManager.GetString("Recover.alertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your wallet with your backup key..
        /// </summary>
        internal static string Recover_header {
            get {
                return ResourceManager.GetString("Recover.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Recover_next {
            get {
                return ResourceManager.GetString("Recover.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Wallet.
        /// </summary>
        internal static string Recover_title {
            get {
                return ResourceManager.GetString("Recover.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup recovery key for the wallet you want to recover..
        /// </summary>
        internal static string RecoverEntry_header {
            get {
                return ResourceManager.GetString("RecoverEntry.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Backup Recovery Key.
        /// </summary>
        internal static string RecoverEntry_title {
            get {
                return ResourceManager.GetString("RecoverEntry.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Recovery_Close {
            get {
                return ResourceManager.GetString("Recovery.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Bitcoin Address.
        /// </summary>
        internal static string Scan_Title {
            get {
                return ResourceManager.GetString("Scan.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Copied..
        /// </summary>
        internal static string SecretContentView_textCopied {
            get {
                return ResourceManager.GetString("SecretContentView.textCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recovery Key.
        /// </summary>
        internal static string Security_backupRecoveryKey {
            get {
                return ResourceManager.GetString("Security.backupRecoveryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometrics.
        /// </summary>
        internal static string Security_biometrics {
            get {
                return ResourceManager.GetString("Security.biometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Security_close {
            get {
                return ResourceManager.GetString("Security.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Security_pin {
            get {
                return ResourceManager.GetString("Security.pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security_title {
            get {
                return ResourceManager.GetString("Security.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveniently unlock your wallet and send money up to a set limit..
        /// </summary>
        internal static string SecurityCenter_fingerprintDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Authentication.
        /// </summary>
        internal static string SecurityCenter_fingerprintHeaderAndroid {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch ID.
        /// </summary>
        internal static string SecurityCenter_fingerprintHeaderIOS {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all security features for maximum protection..
        /// </summary>
        internal static string SecurityCenter_header {
            get {
                return ResourceManager.GetString("SecurityCenter.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only way to access your bitcoin if you lose or upgrade your phone..
        /// </summary>
        internal static string SecurityCenter_mnemonicDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Recovery Key.
        /// </summary>
        internal static string SecurityCenter_mnemonicHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protects your wallet from unauthorized users..
        /// </summary>
        internal static string SecurityCenter_pinDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.pinDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Digit PIN.
        /// </summary>
        internal static string SecurityCenter_pinHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.pinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Center.
        /// </summary>
        internal static string SecurityCenter_title {
            get {
                return ResourceManager.GetString("SecurityCenter.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Seed_next {
            get {
                return ResourceManager.GetString("Seed.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down each word in order and store it in a safe place..
        /// </summary>
        internal static string Seed_subheader {
            get {
                return ResourceManager.GetString("Seed.subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Key.
        /// </summary>
        internal static string Seed_title {
            get {
                return ResourceManager.GetString("Seed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address {0} is on your clipboard would you like to use it to send Bitcoin to it?.
        /// </summary>
        internal static string Send_addressDetectedOnClipboardMessage {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Detected On Clipboard.
        /// </summary>
        internal static string Send_addressDetectedOnClipboardTitle {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Send_amount {
            get {
                return ResourceManager.GetString("Send.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send_buttonSend {
            get {
                return ResourceManager.GetString("Send.buttonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Send_clear {
            get {
                return ResourceManager.GetString("Send.clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        internal static string Send_economyFee {
            get {
                return ResourceManager.GetString("Send.economyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Confirmation.
        /// </summary>
        internal static string Send_estConfirmation {
            get {
                return ResourceManager.GetString("Send.estConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee (sats/byte).
        /// </summary>
        internal static string Send_fee {
            get {
                return ResourceManager.GetString("Send.fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Send_highFee {
            get {
                return ResourceManager.GetString("Send.highFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Send_normalFee {
            get {
                return ResourceManager.GetString("Send.normalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Send_paste {
            get {
                return ResourceManager.GetString("Send.paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Send_scan {
            get {
                return ResourceManager.GetString("Send.scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bitcoin.
        /// </summary>
        internal static string Send_title {
            get {
                return ResourceManager.GetString("Send.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Send_to {
            get {
                return ResourceManager.GetString("Send.to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Transaction?.
        /// </summary>
        internal static string Send_transaction {
            get {
                return ResourceManager.GetString("Send.transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Send_transactionCancel {
            get {
                return ResourceManager.GetString("Send.transactionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Fee.
        /// </summary>
        internal static string Send_transactionFee {
            get {
                return ResourceManager.GetString("Send.transactionFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send {0} ({1} + {2}) BTC to {3}?.
        /// </summary>
        internal static string Send_transactionMessage {
            get {
                return ResourceManager.GetString("Send.transactionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Send_transactionOk {
            get {
                return ResourceManager.GetString("Send.transactionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successful, waiting for confirmation..
        /// </summary>
        internal static string Send_transactionSentMessage {
            get {
                return ResourceManager.GetString("Send.transactionSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_button {
            get {
                return ResourceManager.GetString("Settings.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TransactionDetails_amountTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.amountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed in Block.
        /// </summary>
        internal static string TransactionDetails_confirmedBlockTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.confirmedBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string TransactionDetails_memoTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.memoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received At This Address.
        /// </summary>
        internal static string TransactionDetails_receivedAddressTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.receivedAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To This Address.
        /// </summary>
        internal static string TransactionDetails_sendAddressTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.sendAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TransactionDetails_statusTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.statusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionDetails_title {
            get {
                return ResourceManager.GetString("TransactionDetails.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Transaction ID.
        /// </summary>
        internal static string TransactionDetails_transactionIdTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.transactionIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Confirmation.
        /// </summary>
        internal static string Transactions_awaitingConfirmation {
            get {
                return ResourceManager.GetString("Transactions.awaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Transactions_confirmed {
            get {
                return ResourceManager.GetString("Transactions.confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions received yet.
        /// </summary>
        internal static string Transactions_empty {
            get {
                return ResourceManager.GetString("Transactions.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get An Address.
        /// </summary>
        internal static string Transactions_empty_button {
            get {
                return ResourceManager.GetString("Transactions.empty.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At:.
        /// </summary>
        internal static string Transactions_isSendAt {
            get {
                return ResourceManager.GetString("Transactions.isSendAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string Transactions_isSendTo {
            get {
                return ResourceManager.GetString("Transactions.isSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONS.
        /// </summary>
        internal static string Transactions_title {
            get {
                return ResourceManager.GetString("Transactions.title", resourceCulture);
            }
        }
    }
}
