//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet.UI.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet.UI.Locale.LocaleResources", typeof(LocaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard.create", resourceCulture);
            }
        }
        
        internal static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard.recover", resourceCulture);
            }
        }
        
        internal static string Dashboard_send {
            get {
                return ResourceManager.GetString("Dashboard.send", resourceCulture);
            }
        }
        
        internal static string Dashboard_receive {
            get {
                return ResourceManager.GetString("Dashboard.receive", resourceCulture);
            }
        }
        
        internal static string Dashboard_menu {
            get {
                return ResourceManager.GetString("Dashboard.menu", resourceCulture);
            }
        }
        
        internal static string Seed_title {
            get {
                return ResourceManager.GetString("Seed.title", resourceCulture);
            }
        }
        
        internal static string Seed_next {
            get {
                return ResourceManager.GetString("Seed.next", resourceCulture);
            }
        }
        
        internal static string Seed_subheader {
            get {
                return ResourceManager.GetString("Seed.subheader", resourceCulture);
            }
        }
        
        internal static string Backup_title {
            get {
                return ResourceManager.GetString("Backup.title", resourceCulture);
            }
        }
        
        internal static string Backup_button {
            get {
                return ResourceManager.GetString("Backup.button", resourceCulture);
            }
        }
        
        internal static string Backup_header {
            get {
                return ResourceManager.GetString("Backup.header", resourceCulture);
            }
        }
        
        internal static string Backup_subheader {
            get {
                return ResourceManager.GetString("Backup.subheader", resourceCulture);
            }
        }
        
        internal static string BackupConfirm_header {
            get {
                return ResourceManager.GetString("BackupConfirm.header", resourceCulture);
            }
        }
        
        internal static string BackupConfirm_warning {
            get {
                return ResourceManager.GetString("BackupConfirm.warning", resourceCulture);
            }
        }
        
        internal static string BackupConfirm_exercise {
            get {
                return ResourceManager.GetString("BackupConfirm.exercise", resourceCulture);
            }
        }
        
        internal static string BackupWord_title {
            get {
                return ResourceManager.GetString("BackupWord.title", resourceCulture);
            }
        }
        
        internal static string BackupWord_next {
            get {
                return ResourceManager.GetString("BackupWord.next", resourceCulture);
            }
        }
        
        internal static string BackupWord_previous {
            get {
                return ResourceManager.GetString("BackupWord.previous", resourceCulture);
            }
        }
        
        internal static string BackupWord_header {
            get {
                return ResourceManager.GetString("BackupWord.header", resourceCulture);
            }
        }
        
        internal static string Pin_setTitle {
            get {
                return ResourceManager.GetString("Pin.setTitle", resourceCulture);
            }
        }
        
        internal static string Pin_redoTitle {
            get {
                return ResourceManager.GetString("Pin.redoTitle", resourceCulture);
            }
        }
        
        internal static string Pin_updateTitle {
            get {
                return ResourceManager.GetString("Pin.updateTitle", resourceCulture);
            }
        }
        
        internal static string Pin_updateHeader {
            get {
                return ResourceManager.GetString("Pin.updateHeader", resourceCulture);
            }
        }
        
        internal static string Pin_header {
            get {
                return ResourceManager.GetString("Pin.header", resourceCulture);
            }
        }
        
        internal static string Pin_warning {
            get {
                return ResourceManager.GetString("Pin.warning", resourceCulture);
            }
        }
        
        internal static string Pin_enter {
            get {
                return ResourceManager.GetString("Pin.enter", resourceCulture);
            }
        }
        
        internal static string Recover_title {
            get {
                return ResourceManager.GetString("Recover.title", resourceCulture);
            }
        }
        
        internal static string Recover_header {
            get {
                return ResourceManager.GetString("Recover.header", resourceCulture);
            }
        }
        
        internal static string Recover_next {
            get {
                return ResourceManager.GetString("Recover.next", resourceCulture);
            }
        }
        
        internal static string RecoverEntry_header {
            get {
                return ResourceManager.GetString("RecoverEntry.header", resourceCulture);
            }
        }
        
        internal static string RecoverEntry_title {
            get {
                return ResourceManager.GetString("RecoverEntry.title", resourceCulture);
            }
        }
        
        internal static string Recover_alertTitle {
            get {
                return ResourceManager.GetString("Recover.alertTitle", resourceCulture);
            }
        }
        
        internal static string Recover_alertHeader {
            get {
                return ResourceManager.GetString("Recover.alertHeader", resourceCulture);
            }
        }
        
        internal static string Recover_alertButton {
            get {
                return ResourceManager.GetString("Recover.alertButton", resourceCulture);
            }
        }
        
        internal static string Done_button {
            get {
                return ResourceManager.GetString("Done.button", resourceCulture);
            }
        }
        
        internal static string Send_title {
            get {
                return ResourceManager.GetString("Send.title", resourceCulture);
            }
        }
        
        internal static string Send_to {
            get {
                return ResourceManager.GetString("Send.to", resourceCulture);
            }
        }
        
        internal static string Send_scan {
            get {
                return ResourceManager.GetString("Send.scan", resourceCulture);
            }
        }
        
        internal static string Send_paste {
            get {
                return ResourceManager.GetString("Send.paste", resourceCulture);
            }
        }
        
        internal static string Send_amount {
            get {
                return ResourceManager.GetString("Send.amount", resourceCulture);
            }
        }
        
        internal static string Send_transaction {
            get {
                return ResourceManager.GetString("Send.transaction", resourceCulture);
            }
        }
        
        internal static string Send_transactionMessage {
            get {
                return ResourceManager.GetString("Send.transactionMessage", resourceCulture);
            }
        }
        
        internal static string Send_transactionOk {
            get {
                return ResourceManager.GetString("Send.transactionOk", resourceCulture);
            }
        }
        
        internal static string Send_transactionCancel {
            get {
                return ResourceManager.GetString("Send.transactionCancel", resourceCulture);
            }
        }
        
        internal static string Receive_title {
            get {
                return ResourceManager.GetString("Receive.title", resourceCulture);
            }
        }
        
        internal static string Receive_share {
            get {
                return ResourceManager.GetString("Receive.share", resourceCulture);
            }
        }
        
        internal static string Receive_requestAmount {
            get {
                return ResourceManager.GetString("Receive.requestAmount", resourceCulture);
            }
        }
        
        internal static string Menu_title {
            get {
                return ResourceManager.GetString("Menu.title", resourceCulture);
            }
        }
        
        internal static string Menu_security {
            get {
                return ResourceManager.GetString("Menu.security", resourceCulture);
            }
        }
        
        internal static string Menu_knowledge {
            get {
                return ResourceManager.GetString("Menu.knowledge", resourceCulture);
            }
        }
        
        internal static string Menu_settings {
            get {
                return ResourceManager.GetString("Menu.settings", resourceCulture);
            }
        }
        
        internal static string Menu_lock {
            get {
                return ResourceManager.GetString("Menu.lock", resourceCulture);
            }
        }
        
        internal static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        internal static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        internal static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_title {
            get {
                return ResourceManager.GetString("SecurityCenter.title", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_header {
            get {
                return ResourceManager.GetString("SecurityCenter.header", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_pinHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.pinHeader", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_pinDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.pinDetail", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintHeaderIOS {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderIOS", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintHeaderAndroid {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderAndroid", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintDetail", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_mnemonicHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicHeader", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_mnemonicDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicDetail", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_header {
            get {
                return ResourceManager.GetString("FingerprintAuth.header", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_switchLabelIOS {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchLabelIOS", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_switchAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchAndroid", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_spendingLimit {
            get {
                return ResourceManager.GetString("FingerprintAuth.spendingLimit", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_subheader {
            get {
                return ResourceManager.GetString("FingerprintAuth.subheader", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_limitButtonIOS {
            get {
                return ResourceManager.GetString("FingerprintAuth.limitButtonIOS", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_limitButtonAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.limitButtonAndroid", resourceCulture);
            }
        }
        
        internal static string Send_addressDetectedOnClipboardTitle {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardTitle", resourceCulture);
            }
        }
        
        internal static string Send_addressDetectedOnClipboardMessage {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardMessage", resourceCulture);
            }
        }
        
        internal static string Transactions_title {
            get {
                return ResourceManager.GetString("Transactions.title", resourceCulture);
            }
        }
        
        internal static string Transactions_empty {
            get {
                return ResourceManager.GetString("Transactions.empty", resourceCulture);
            }
        }
        
        internal static string Transactions_empty_button {
            get {
                return ResourceManager.GetString("Transactions.empty.button", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_title {
            get {
                return ResourceManager.GetString("TransactionDetails.title", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_statusTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.statusTitle", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_memoTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.memoTitle", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_amountTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.amountTitle", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_transactionIdTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.transactionIdTitle", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_confirmedBlockTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.confirmedBlockTitle", resourceCulture);
            }
        }
        
        internal static string NowLoading_text {
            get {
                return ResourceManager.GetString("NowLoading.text", resourceCulture);
            }
        }
        
        internal static string Accounts_title {
            get {
                return ResourceManager.GetString("Accounts.title", resourceCulture);
            }
        }
        
        internal static string AccountSelection_title {
            get {
                return ResourceManager.GetString("AccountSelection.title", resourceCulture);
            }
        }
        
        internal static string AccountSelection_header {
            get {
                return ResourceManager.GetString("AccountSelection.header", resourceCulture);
            }
        }
        
        internal static string AccountSelection_subheader {
            get {
                return ResourceManager.GetString("AccountSelection.subheader", resourceCulture);
            }
        }
        
        internal static string AddAccount_title {
            get {
                return ResourceManager.GetString("AddAccount.title", resourceCulture);
            }
        }
        
        internal static string AddAccount_header {
            get {
                return ResourceManager.GetString("AddAccount.header", resourceCulture);
            }
        }
        
        internal static string AddAccount_subheader {
            get {
                return ResourceManager.GetString("AddAccount.subheader", resourceCulture);
            }
        }
        
        internal static string AddAccount_button {
            get {
                return ResourceManager.GetString("AddAccount.button", resourceCulture);
            }
        }
        
        internal static string AddAccount_close {
            get {
                return ResourceManager.GetString("AddAccount.close", resourceCulture);
            }
        }
        
        internal static string AddAccount_entry {
            get {
                return ResourceManager.GetString("AddAccount.entry", resourceCulture);
            }
        }
        
        internal static string AddAccount_options {
            get {
                return ResourceManager.GetString("AddAccount.options", resourceCulture);
            }
        }
        
        internal static string AddAccount_color {
            get {
                return ResourceManager.GetString("AddAccount.color", resourceCulture);
            }
        }
        
        internal static string AddAccount_createButton {
            get {
                return ResourceManager.GetString("AddAccount.createButton", resourceCulture);
            }
        }
        
        internal static string Backup_close {
            get {
                return ResourceManager.GetString("Backup.close", resourceCulture);
            }
        }
        
        internal static string Backup_skip {
            get {
                return ResourceManager.GetString("Backup.skip", resourceCulture);
            }
        }
        
        internal static string AccountSettings_Title {
            get {
                return ResourceManager.GetString("AccountSettings.Title", resourceCulture);
            }
        }
        
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        internal static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings.Close", resourceCulture);
            }
        }
        
        internal static string PinPad_Title {
            get {
                return ResourceManager.GetString("PinPad.Title", resourceCulture);
            }
        }
        
        internal static string Recovery_Close {
            get {
                return ResourceManager.GetString("Recovery.Close", resourceCulture);
            }
        }
        
        internal static string Send_buttonSend {
            get {
                return ResourceManager.GetString("Send.buttonSend", resourceCulture);
            }
        }
        
        internal static string Send_fee {
            get {
                return ResourceManager.GetString("Send.fee", resourceCulture);
            }
        }
        
        internal static string Ordinal_eighth {
            get {
                return ResourceManager.GetString("Ordinal.eighth", resourceCulture);
            }
        }
        
        internal static string Ordinal_eleventh {
            get {
                return ResourceManager.GetString("Ordinal.eleventh", resourceCulture);
            }
        }
        
        internal static string Ordinal_fifth {
            get {
                return ResourceManager.GetString("Ordinal.fifth", resourceCulture);
            }
        }
        
        internal static string Ordinal_first {
            get {
                return ResourceManager.GetString("Ordinal.first", resourceCulture);
            }
        }
        
        internal static string Ordinal_fourth {
            get {
                return ResourceManager.GetString("Ordinal.fourth", resourceCulture);
            }
        }
        
        internal static string Ordinal_ninth {
            get {
                return ResourceManager.GetString("Ordinal.ninth", resourceCulture);
            }
        }
        
        internal static string Ordinal_second {
            get {
                return ResourceManager.GetString("Ordinal.second", resourceCulture);
            }
        }
        
        internal static string Ordinal_seventh {
            get {
                return ResourceManager.GetString("Ordinal.seventh", resourceCulture);
            }
        }
        
        internal static string Ordinal_sixth {
            get {
                return ResourceManager.GetString("Ordinal.sixth", resourceCulture);
            }
        }
        
        internal static string Ordinal_tenth {
            get {
                return ResourceManager.GetString("Ordinal.tenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_third {
            get {
                return ResourceManager.GetString("Ordinal.third", resourceCulture);
            }
        }
        
        internal static string Ordinal_twelveth {
            get {
                return ResourceManager.GetString("Ordinal.twelveth", resourceCulture);
            }
        }
        
        internal static string Alert_irreversible {
            get {
                return ResourceManager.GetString("Alert.irreversible", resourceCulture);
            }
        }
        
        internal static string Button_no {
            get {
                return ResourceManager.GetString("Button.no", resourceCulture);
            }
        }
        
        internal static string Button_yes {
            get {
                return ResourceManager.GetString("Button.yes", resourceCulture);
            }
        }
        
        internal static string Ordinal_eighteenth {
            get {
                return ResourceManager.GetString("Ordinal.eighteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_fifteenth {
            get {
                return ResourceManager.GetString("Ordinal.fifteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_fourteenth {
            get {
                return ResourceManager.GetString("Ordinal.fourteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_nineteenth {
            get {
                return ResourceManager.GetString("Ordinal.nineteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_seventeenth {
            get {
                return ResourceManager.GetString("Ordinal.seventeenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_sixteenth {
            get {
                return ResourceManager.GetString("Ordinal.sixteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_thirteenth {
            get {
                return ResourceManager.GetString("Ordinal.thirteenth", resourceCulture);
            }
        }
        
        internal static string Ordinal_twentieth {
            get {
                return ResourceManager.GetString("Ordinal.twentieth", resourceCulture);
            }
        }
        
        internal static string Ordinal_twenty_first {
            get {
                return ResourceManager.GetString("Ordinal.twenty-first", resourceCulture);
            }
        }
        
        internal static string Ordinal_twenty_fourth {
            get {
                return ResourceManager.GetString("Ordinal.twenty-fourth", resourceCulture);
            }
        }
        
        internal static string Ordinal_twenty_second {
            get {
                return ResourceManager.GetString("Ordinal.twenty-second", resourceCulture);
            }
        }
        
        internal static string Ordinal_twenty_third {
            get {
                return ResourceManager.GetString("Ordinal.twenty-third", resourceCulture);
            }
        }
        
        internal static string Scan_Title {
            get {
                return ResourceManager.GetString("Scan.Title", resourceCulture);
            }
        }
        
        internal static string Address_copied {
            get {
                return ResourceManager.GetString("Address.copied", resourceCulture);
            }
        }
        
        internal static string Error_ok {
            get {
                return ResourceManager.GetString("Error.ok", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_receivedAddressTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.receivedAddressTitle", resourceCulture);
            }
        }
        
        internal static string TransactionDetails_sendAddressTitle {
            get {
                return ResourceManager.GetString("TransactionDetails.sendAddressTitle", resourceCulture);
            }
        }
        
        internal static string Settings_button {
            get {
                return ResourceManager.GetString("Settings.button", resourceCulture);
            }
        }
        
        internal static string Send_economyFee {
            get {
                return ResourceManager.GetString("Send.economyFee", resourceCulture);
            }
        }
        
        internal static string Send_estConfirmation {
            get {
                return ResourceManager.GetString("Send.estConfirmation", resourceCulture);
            }
        }
        
        internal static string Send_highFee {
            get {
                return ResourceManager.GetString("Send.highFee", resourceCulture);
            }
        }
        
        internal static string Send_normalFee {
            get {
                return ResourceManager.GetString("Send.normalFee", resourceCulture);
            }
        }
        
        internal static string Send_transactionFee {
            get {
                return ResourceManager.GetString("Send.transactionFee", resourceCulture);
            }
        }
        
        internal static string Transactions_awaitingConfirmation {
            get {
                return ResourceManager.GetString("Transactions.awaitingConfirmation", resourceCulture);
            }
        }
        
        internal static string Transactions_confirmed {
            get {
                return ResourceManager.GetString("Transactions.confirmed", resourceCulture);
            }
        }
        
        internal static string Transactions_isSendAt {
            get {
                return ResourceManager.GetString("Transactions.isSendAt", resourceCulture);
            }
        }
        
        internal static string Transactions_isSendTo {
            get {
                return ResourceManager.GetString("Transactions.isSendTo", resourceCulture);
            }
        }
        
        internal static string AckRisk_button {
            get {
                return ResourceManager.GetString("AckRisk.button", resourceCulture);
            }
        }
        
        internal static string AckRisk_term1 {
            get {
                return ResourceManager.GetString("AckRisk.term1", resourceCulture);
            }
        }
        
        internal static string AckRisk_term2 {
            get {
                return ResourceManager.GetString("AckRisk.term2", resourceCulture);
            }
        }
        
        internal static string AckRisk_term3 {
            get {
                return ResourceManager.GetString("AckRisk.term3", resourceCulture);
            }
        }
        
        internal static string AckRisk_term4 {
            get {
                return ResourceManager.GetString("AckRisk.term4", resourceCulture);
            }
        }
        
        internal static string AckRisk_title {
            get {
                return ResourceManager.GetString("AckRisk.title", resourceCulture);
            }
        }
        
        internal static string NewWallet_body {
            get {
                return ResourceManager.GetString("NewWallet.body", resourceCulture);
            }
        }
        
        internal static string NewWallet_button {
            get {
                return ResourceManager.GetString("NewWallet.button", resourceCulture);
            }
        }
        
        internal static string NewWallet_header {
            get {
                return ResourceManager.GetString("NewWallet.header", resourceCulture);
            }
        }
        
        internal static string NewWallet_title {
            get {
                return ResourceManager.GetString("NewWallet.title", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_description {
            get {
                return ResourceManager.GetString("AccountTypeSelection.description", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_doneButton {
            get {
                return ResourceManager.GetString("AccountTypeSelection.doneButton", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_legacyDescription {
            get {
                return ResourceManager.GetString("AccountTypeSelection.legacyDescription", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_legacyTitle {
            get {
                return ResourceManager.GetString("AccountTypeSelection.legacyTitle", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_standardDescription {
            get {
                return ResourceManager.GetString("AccountTypeSelection.standardDescription", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_standardTitle {
            get {
                return ResourceManager.GetString("AccountTypeSelection.standardTitle", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_title {
            get {
                return ResourceManager.GetString("AccountTypeSelection.title", resourceCulture);
            }
        }
        
        internal static string AccountTypeSelection_pleaseSelect {
            get {
                return ResourceManager.GetString("AccountTypeSelection.pleaseSelect", resourceCulture);
            }
        }
    }
}
