//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet2.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet2.LocaleResources", typeof(LocaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard_create", resourceCulture);
            }
        }
        
        internal static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard_recover", resourceCulture);
            }
        }
        
        internal static string Dashboard_send {
            get {
                return ResourceManager.GetString("Dashboard.send", resourceCulture);
            }
        }
        
        internal static string Dashboard_receive {
            get {
                return ResourceManager.GetString("Dashboard.receive", resourceCulture);
            }
        }
        
        internal static string Dashboard_menu {
            get {
                return ResourceManager.GetString("Dashboard.menu", resourceCulture);
            }
        }
        
        internal static string Seed_title {
            get {
                return ResourceManager.GetString("Seed.title", resourceCulture);
            }
        }
        
        internal static string Seed_next {
            get {
                return ResourceManager.GetString("Seed.next", resourceCulture);
            }
        }
        
        internal static string Seed_subheader {
            get {
                return ResourceManager.GetString("Seed.subheader", resourceCulture);
            }
        }
        
        internal static string Backup_title {
            get {
                return ResourceManager.GetString("Backup.title", resourceCulture);
            }
        }
        
        internal static string Backup_subheader {
            get {
                return ResourceManager.GetString("Backup.subheader", resourceCulture);
            }
        }
        
        internal static string Backup_button {
            get {
                return ResourceManager.GetString("Backup.button", resourceCulture);
            }
        }
        
        internal static string Backup_wordheader {
            get {
                return ResourceManager.GetString("Backup.wordheader", resourceCulture);
            }
        }
        
        internal static string Backup_previous {
            get {
                return ResourceManager.GetString("Backup.previous", resourceCulture);
            }
        }
        
        internal static string ConfirmBackup_header {
            get {
                return ResourceManager.GetString("ConfirmBackup.header", resourceCulture);
            }
        }
        
        internal static string Pin_setTitle {
            get {
                return ResourceManager.GetString("Pin.setTitle", resourceCulture);
            }
        }
        
        internal static string Pin_redoTitle {
            get {
                return ResourceManager.GetString("Pin.redoTitle", resourceCulture);
            }
        }
        
        internal static string Pin_updateTitle {
            get {
                return ResourceManager.GetString("Pin.updateTitle", resourceCulture);
            }
        }
        
        internal static string Pin_updateHeader {
            get {
                return ResourceManager.GetString("Pin.updateHeader", resourceCulture);
            }
        }
        
        internal static string Pin_header {
            get {
                return ResourceManager.GetString("Pin.header", resourceCulture);
            }
        }
        
        internal static string Pin_warning {
            get {
                return ResourceManager.GetString("Pin.warning", resourceCulture);
            }
        }
        
        internal static string Pin_enter {
            get {
                return ResourceManager.GetString("Pin.enter", resourceCulture);
            }
        }
        
        internal static string Recover_title {
            get {
                return ResourceManager.GetString("Recover.title", resourceCulture);
            }
        }
        
        internal static string Recover_header {
            get {
                return ResourceManager.GetString("Recover.header", resourceCulture);
            }
        }
        
        internal static string Recover_next {
            get {
                return ResourceManager.GetString("Recover.next", resourceCulture);
            }
        }
        
        internal static string Recover_entryHeader {
            get {
                return ResourceManager.GetString("Recover.entryHeader", resourceCulture);
            }
        }
        
        internal static string Recover_alertTitle {
            get {
                return ResourceManager.GetString("Recover.alertTitle", resourceCulture);
            }
        }
        
        internal static string Recover_alertHeader {
            get {
                return ResourceManager.GetString("Recover.alertHeader", resourceCulture);
            }
        }
        
        internal static string Recover_alertButton {
            get {
                return ResourceManager.GetString("Recover.alertButton", resourceCulture);
            }
        }
        
        internal static string Send_title {
            get {
                return ResourceManager.GetString("Send.title", resourceCulture);
            }
        }
        
        internal static string Send_to {
            get {
                return ResourceManager.GetString("Send.to", resourceCulture);
            }
        }
        
        internal static string Send_scan {
            get {
                return ResourceManager.GetString("Send.scan", resourceCulture);
            }
        }
        
        internal static string Send_paste {
            get {
                return ResourceManager.GetString("Send.paste", resourceCulture);
            }
        }
        
        internal static string Send_amount {
            get {
                return ResourceManager.GetString("Send.amount", resourceCulture);
            }
        }
        
        internal static string Receive_title {
            get {
                return ResourceManager.GetString("Receive.title", resourceCulture);
            }
        }
        
        internal static string Receive_share {
            get {
                return ResourceManager.GetString("Receive.share", resourceCulture);
            }
        }
        
        internal static string Receive_requestAmount {
            get {
                return ResourceManager.GetString("Receive.requestAmount", resourceCulture);
            }
        }
        
        internal static string Menu_title {
            get {
                return ResourceManager.GetString("Menu.title", resourceCulture);
            }
        }
        
        internal static string Menu_security {
            get {
                return ResourceManager.GetString("Menu.security", resourceCulture);
            }
        }
        
        internal static string Menu_knowledge {
            get {
                return ResourceManager.GetString("Menu.knowledge", resourceCulture);
            }
        }
        
        internal static string Menu_settings {
            get {
                return ResourceManager.GetString("Menu.settings", resourceCulture);
            }
        }
        
        internal static string Menu_lock {
            get {
                return ResourceManager.GetString("Menu.lock", resourceCulture);
            }
        }
        
        internal static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        internal static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        internal static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_title {
            get {
                return ResourceManager.GetString("SecurityCenter.title", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_header {
            get {
                return ResourceManager.GetString("SecurityCenter.header", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_pinHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.pinHeader", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_pinDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.pinDetail", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintHeaderIOS {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderIOS", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintHeaderAndroid {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintHeaderAndroid", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_fingerprintDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.fingerprintDetail", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_mnemonicHeader {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicHeader", resourceCulture);
            }
        }
        
        internal static string SecurityCenter_mnemonicDetail {
            get {
                return ResourceManager.GetString("SecurityCenter.mnemonicDetail", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_header {
            get {
                return ResourceManager.GetString("FingerprintAuth.header", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_switchLabelIOS {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchLabelIOS", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_switchAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.switchAndroid", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_spendingLimit {
            get {
                return ResourceManager.GetString("FingerprintAuth.spendingLimit", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_subheader {
            get {
                return ResourceManager.GetString("FingerprintAuth.subheader", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_limitButtonIOS {
            get {
                return ResourceManager.GetString("FingerprintAuth.limitButtonIOS", resourceCulture);
            }
        }
        
        internal static string FingerprintAuth_limitButtonAndroid {
            get {
                return ResourceManager.GetString("FingerprintAuth.limitButtonAndroid", resourceCulture);
            }
        }
        
        internal static string Send_addressDetectedOnClipboardTitle {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardTitle", resourceCulture);
            }
        }
        
        internal static string Send_addressDetectedOnClipboardMessage {
            get {
                return ResourceManager.GetString("Send.addressDetectedOnClipboardMessage", resourceCulture);
            }
        }
    }
}
