//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet2.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet2.LocaleResources", typeof(LocaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard_create", resourceCulture);
            }
        }
        
        internal static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard_recover", resourceCulture);
            }
        }
        
        internal static string Dashboard_send {
            get {
                return ResourceManager.GetString("Dashboard.send", resourceCulture);
            }
        }
        
        internal static string Dashboard_receive {
            get {
                return ResourceManager.GetString("Dashboard.receive", resourceCulture);
            }
        }
        
        internal static string Dashboard_menu {
            get {
                return ResourceManager.GetString("Dashboard.menu", resourceCulture);
            }
        }
        
        internal static string Seed_title {
            get {
                return ResourceManager.GetString("Seed.title", resourceCulture);
            }
        }
        
        internal static string Seed_next {
            get {
                return ResourceManager.GetString("Seed.next", resourceCulture);
            }
        }
        
        internal static string Seed_subheader {
            get {
                return ResourceManager.GetString("Seed.subheader", resourceCulture);
            }
        }
        
        internal static string Backup_title {
            get {
                return ResourceManager.GetString("Backup.title", resourceCulture);
            }
        }
        
        internal static string Backup_subheader {
            get {
                return ResourceManager.GetString("Backup.subheader", resourceCulture);
            }
        }
        
        internal static string Backup_button {
            get {
                return ResourceManager.GetString("Backup.button", resourceCulture);
            }
        }
        
        internal static string Backup_wordheader {
            get {
                return ResourceManager.GetString("Backup.wordheader", resourceCulture);
            }
        }
        
        internal static string ConfirmBackup_header {
            get {
                return ResourceManager.GetString("ConfirmBackup.header", resourceCulture);
            }
        }
        
        internal static string Pin_setTitle {
            get {
                return ResourceManager.GetString("Pin.setTitle", resourceCulture);
            }
        }
        
        internal static string Pin_redoTitle {
            get {
                return ResourceManager.GetString("Pin.redoTitle", resourceCulture);
            }
        }
        
        internal static string Pin_header {
            get {
                return ResourceManager.GetString("Pin.header", resourceCulture);
            }
        }
        
        internal static string Pin_warning {
            get {
                return ResourceManager.GetString("Pin.warning", resourceCulture);
            }
        }
    }
}
