//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HodlWallet2.Locale {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HodlWallet2.Locale.LocaleResources.es", typeof(LocaleResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Onboard_create {
            get {
                return ResourceManager.GetString("Onboard.create", resourceCulture);
            }
        }
        
        internal static string Onboard_recover {
            get {
                return ResourceManager.GetString("Onboard.recover", resourceCulture);
            }
        }
        
        internal static string Menu_resyncWallet {
            get {
                return ResourceManager.GetString("Menu.resyncWallet", resourceCulture);
            }
        }
        
        internal static string Menu_restoreWallet {
            get {
                return ResourceManager.GetString("Menu.restoreWallet", resourceCulture);
            }
        }
        
        internal static string Menu_wipeWallet {
            get {
                return ResourceManager.GetString("Menu.wipeWallet", resourceCulture);
            }
        }
    }
}
